os:
- linux
language: node_js
node_js:
- '8'

script:
- git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
- git fetch origin
- git checkout $TRAVIS_BRANCH || git checkout -b $TRAVIS_BRANCH
- yarn test

env:
  global:
  - secure: efiaEYLsybC2gRHcAz8vvSaiIwoAaN+yZrzaoScUlG22XRRFgWLRiz7uzKlP1OcSz0z/42cVaxMqfWjPMLx+01XX7K5dhMNOgGT3Zs9+Z76v3TpWIIRdAMqQmxqFSgUOrdE3I3PqTGmqklCHRe6oH/qFC9s6QxjVVMOEIfPsq5Sdnug/zA9yIGmhyPg9k5ciOfOi7ZENiEuIM7Jdz5+sAHeVgM4EZwmGTqppy+6jKNUYT8/37HYwsjv6AveMetRaBHw9Ku/UFhhEuKmrLShBht8T1jQM9y0B3To6N44610+t9QFNGlQwGYLEslgblKWTJo7TD44y7bljGVEh/xp/MNduXnk+hn9lt/3tC3FiyEXnHUAbeNHYsRBIZObJrrdC8rtkPIVuIK4f8QkHdwWAQzfw5QbxqG3R8MtZJ0V1t/o5j+5o9oxfFe6P6P73YjoQWwoMdacAw3Nw5CSXHVDxHZqsJtiPJXYuwr8l1BEPGBD/LwjTGnJAl816a1nf3xz95btGKaFZnBdP5QxtuBQXlYmG56KQGFI+RzA/ehkdUVIhP76jgQ7OfjQ3rVBQFvPRGNQ0fIfW8cDqCVKTouj7SsU7+Pg5dwza7aPsHDDhH/gfM8rYbViDE1qYww0DHdOniyOfokY/auL2Kwn/7rhTddkRNIK4xkNjY9mUtUyO5eU=
  - secure: NUAHHJdTOc7WQVlvCo5f+REW4Go8oRgZh+Aa6rFiwJHqsmi4YeS2m74mRWGh9uxa5fOWgObo3aFDJ5iWLtJOlc8VCa4R1WGLr6xVW0eJVvzk1tJwILqFsQTd8dlk60ZGXgbiTRr8XndDRw/WPrZJg7P1bIXhg50DG5QIFWbnuM4TNoEOa7flts6dkLAOZjpT+StoJ+K3e6AOz8fNfp8tdtz/mv69fAasHdNIpnmYYl72ptsN1MUYfFQmdhuMyosfCUzpWoZvNBVULspI1np+dDYy3ZFCziblDDPWPkYFs+HvAxRPOpsnD4Uolf9cpOpnpA3f7a518COTA+cGcoAhOauqloTSQ6kZ06BoVp53CQ4EaAJxkBRpi8K+QLKPbEUmlBgw/syXUAnIqwA73r/tMZ4rmdcVhZdHTBNwZbjvw+ZkCGR6RM3rCa8U67LLrlz2xN80qdNCgfLwwp94lsg9V2GetpsYtmpJcnbFGZHXHBUO9VrfEICYtIHJDtmPaMv0yn9cbnB1dQ/Va70GQQ/Ico3RqSF3VNOFuW0WBjeFHi7VYDsBT0g3j03ZVedZogMjSD0ll5xHIDh3gV7DzK0qdFVKEqx/C9Fuh0MOjZVoAqNJlSB+UDnAp0rv5lN3vkzeu4xfyG+uz8E2kMesDdwSUJneiR87vWtz1R3nSlfpP7k=
